In [1]:
import numpy as np
import numpy.linalg as alg

EIGEN DECOMPOSITION

In [16]:
ar=np.array([[2.5, -1],[-1, 2.5]])
eigvals, P = alg.eig(ar)
D = np.diag(eigvals)

In [17]:
print("Eigenvalues:\n", eigvals)
print("P:\n", P)
print("D:\n", D)
print("P inverse:\n", alg.inv(P))

Eigenvalues:
 [3.5 1.5]
P:
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
D:
 [[3.5 0. ]
 [0.  1.5]]
P inverse:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [12]:
print("A=P*D*P^-1:\n", np.matmul(P, np.matmul(np.diag(eigvals), alg.inv(P))))

A=P*D*P^-1:
 [[ 2.5 -1. ]
 [-1.   2.5]]


In [22]:
ar=np.array([[1, 2, 3], [3, 2, 1], [2, 1, 3]])
eigvals, P = alg.eig(ar)
D = np.diag(eigvals)

In [23]:
print("Eigenvalues:\n", eigvals)
print("P:\n", P)
print("D:\n", D)
print("P inverse:\n", alg.inv(P))

Eigenvalues:
 [-1.73205081  1.73205081  6.        ]
P:
 [[ 0.78867513  0.21132487  0.57735027]
 [-0.57735027  0.57735027  0.57735027]
 [-0.21132487 -0.78867513  0.57735027]]
D:
 [[-1.73205081  0.          0.        ]
 [ 0.          1.73205081  0.        ]
 [ 0.          0.          6.        ]]
P inverse:
 [[ 0.78867513 -0.57735027 -0.21132487]
 [ 0.21132487  0.57735027 -0.78867513]
 [ 0.57735027  0.57735027  0.57735027]]


In [24]:
print("A=P*D*P^-1:\n", np.matmul(P, np.matmul(np.diag(eigvals), alg.inv(P))))

A=P*D*P^-1:
 [[1. 3. 2.]
 [3. 2. 1.]
 [2. 1. 3.]]


In [25]:
ar=np.array([[1, 2, 3], [3, 2, 1]])
eigvals, P = alg.eig(ar)
D = np.diag(eigvals)

LinAlgError: Last 2 dimensions of the array must be square

CHOLSKEY DECOMPOSITION

In [28]:
ar=np.array([[36,1,13],[1,25,15],[13,15,36]])
L=alg.cholesky(ar)
print("L:\n", L)
LT=np.transpose(L)
print("L^-1:\n", LT)
print(np.matmul(L, LT))

L:
 [[6.         0.         0.        ]
 [0.16666667 4.99722145 0.        ]
 [2.16666667 2.92940568 4.76698415]]
L^-1:
 [[6.         0.16666667 2.16666667]
 [0.         4.99722145 2.92940568]
 [0.         0.         4.76698415]]
[[36.  1. 13.]
 [ 1. 25. 15.]
 [13. 15. 36.]]


In [29]:
ar=np.array([[9,2,13],[2,49,5],[13,5,25]])
L=alg.cholesky(ar)
print("L:\n", L)
LT=np.transpose(L)
print("L^-1:\n", LT)
print(np.matmul(L, LT))

L:
 [[3.         0.         0.        ]
 [0.66666667 6.96818165 0.        ]
 [4.33333333 0.30296442 2.47597148]]
L^-1:
 [[3.         0.66666667 4.33333333]
 [0.         6.96818165 0.30296442]
 [0.         0.         2.47597148]]
[[ 9.  2. 13.]
 [ 2. 49.  5.]
 [13.  5. 25.]]


In [30]:
ar=np.array([[36,1,13],[1,25,15],[13,15,-1]])
L=alg.cholesky(ar)
print("L:\n", L)
LT=np.transpose(L)
print("L^-1:\n", LT)
print(np.matmul(L, LT))

LinAlgError: Matrix is not positive definite

In [31]:
ar=np.array([[36,1,13],[1,25,15]])
L=alg.cholesky(ar)
print("L:\n", L)
LT=np.transpose(L)
print("L^-1:\n", LT)
print(np.matmul(L, LT))

LinAlgError: Last 2 dimensions of the array must be square